//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ictshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhToan
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Phải có tên")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Chiều dài không chính xác")]
        public string HoVaTen { get; set; }

        [Required(ErrorMessage = "Phải có Email")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Chiều dài không chính xác")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Phải Địa Chỉ")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Chiều dài không chính xác")]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Phải có SỐ điện Thoại")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Số điện thoại sai")]
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    }
}
